# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6aaf0534b4419473cce1f7e9877ec655998662d821a02c8ec8cd627308aa280afbadbe666961b5aae53064bf011a1f83d71bf1421dd62ee3953e2c7ff238fedb

test:
  secret_key_base: c78705b47f74e723e3cc64f26c4c5ccb9183150e14c8f6f9881cd0693eaa5945da1813173e2e2a8c160a137744c9bbfe193fd9fdb63825aa0e7a38bd7fd26d1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
